export const GET_NEW_ASSIGNMENTS = 'GET_NEW_ASSIGNMENTS'
export const GET_NEW_ASSIGNMENTS_SUCCESS = 'GET_NEW_ASSIGNMENTS_SUCCESS'
export const GET_NEW_ASSIGNMENTS_FAILURE = 'GET_NEW_ASSIGNMENTS_FAILURE'

export const GET_PAST_ASSIGNMENTS = 'GET_PAST_ASSIGNMENTS'
export const GET_PAST_ASSIGNMENTS_SUCCESS = 'GET_PAST_ASSIGNMENTS_SUCCESS'
export const GET_PAST_ASSIGNMENTS_FAILURE = 'GET_PAST_ASSIGNMENTS_FAILURE'

export const SELECT_ASSIGNMENT = 'SELECT_ASSIGNMENT'

export const GET_ASSIGNMENT_ATTEMPT = 'GET_ASSIGNMENT_ATTEMPT'
export const GET_ASSIGNMENT_ATTEMPT_SUCCESS = 'GET_ASSIGNMENT_ATTEMPT_SUCCESS'
export const GET_ASSIGNMENT_ATTEMPT_FAILURE = 'GET_ASSIGNMENT_ATTEMPT_FAILURE'

export const GET_ASSIGNMENT = 'GET_ASSIGNMENT'
export const GET_ASSIGNMENT_SUCCESS = 'GET_ASSIGNMENT_SUCCESS'
export const GET_ASSIGNMENT_FAILURE = 'GET_ASSIGNMENT_FAILURE'

export const CREATE_ASSIGNMENT_ATTEMPT = 'CREATE_ASSIGNMENT_ATTEMPT'
export const CREATE_ASSIGNMENT_ATTEMPT_SUCCESS = 'CREATE_ASSIGNMENT_ATTEMPT_SUCCESS'
export const CREATE_ASSIGNMENT_ATTEMPT_FAILURE = 'CREATE_ASSIGNMENT_ATTEMPT_FAILURE'

export const SAVE_ANSWER = 'SAVE_ANSWER'

export const SUBMIT_ASSIGNMENT = 'SUBMIT_ASSIGNMENT'
export const SUBMIT_ASSIGNMENT_SUCCESS = 'SUBMIT_ASSIGNMENT_SUCCESS'
export const SUBMIT_ASSIGNMENT_FAILURE = 'SUBMIT_ASSIGNMENT_FAILURE'
