export const GET_USER_TOPICS = 'GET_USER_TOPICS'
export const GET_USER_TOPICS_SUCCESS = 'GET_USER_TOPICS_SUCCESS'
export const GET_USER_TOPICS_FAILURE = 'GET_USER_TOPICS_FAILURE'

export const GET_USER_TOPIC_LESSONS = 'GET_USER_TOPIC_LESSONS'
export const GET_USER_TOPIC_LESSONS_SUCCESS = 'GET_USER_TOPIC_LESSONS_SUCCESS'
export const GET_USER_TOPIC_LESSONS_FAILURE = 'GET_USER_TOPIC_LESSONS_FAILURE'

export const SELECT_TOPIC = 'SELECT_TOPIC'
export const SELECT_LESSON = 'SELECT_LESSON'
export const COMPLETED_LESSON = 'COMPLETED_LESSON';
export const COMPLETED_LESSON_SUCCESS = 'COMPLETED_LESSON_SUCCESS';
export const COMPLETED_LESSON_FAILURE = 'COMPLETED_LESSON_FAILURE';


export const GET_LESSON = 'GET_LESSON'
export const GET_LESSON_SUCCESS = 'GET_LESSON_SUCCESS'
export const GET_LESSON_FAILURE = 'GET_LESSON_FAILURE'

export const GET_RECENT_LESSONS = 'GET_RECENT_LESSONS'
export const GET_RECENT_LESSONS_SUCCESS = 'GET_RECENT_LESSONS_SUCCESS'
export const GET_RECENT_LESSONS_FAILURE = 'GET_RECENT_LESSONS_FAILURE'

export const GET_INCOMPLETE_LESSONS_COUNT = 'GET_INCOMPLETE_LESSONS_COUNT'
export const GET_INCOMPLETE_LESSONS_COUNT_SUCCESS = 'GET_INCOMPLETE_LESSONS_COUNT_SUCCESS'
export const GET_INCOMPLETE_LESSONS_COUNT_FAILURE = 'GET_INCOMPLETE_LESSONS_COUNT_FAILURE'
