export const GET_USER_TOPICS = 'GET_USER_TOPICS'
export const GET_USER_TOPICS_SUCCESS = 'GET_USER_TOPICS_SUCCESS'
export const GET_USER_TOPICS_FAILURE = 'GET_USER_TOPICS_FAILURE'

export const GET_USER_TOPIC_LESSONS = 'GET_USER_TOPIC_LESSONS'
export const GET_USER_TOPIC_LESSONS_SUCCESS = 'GET_USER_TOPIC_LESSONS_SUCCESS'
export const GET_USER_TOPIC_LESSONS_FAILURE = 'GET_USER_TOPIC_LESSONS_FAILURE'

export const SELECT_TOPIC = 'SELECT_TOPIC'
export const SELECT_LESSON = 'SELECT_LESSON'