export const GET_TESTS = 'GET_TESTS'
export const GET_TESTS_SUCCESS = 'GET_TESTS_SUCCESS'
export const GET_TESTS_FAILURE = 'GET_TESTS_FAILURE'

export const NEW_TEST_ATTEMPT = 'NEW_TEST_ATTEMPT'
export const NEW_TEST_ATTEMPT_SUCCESS = 'NEW_TEST_ATTEMPT_SUCCESS'
export const NEW_TEST_ATTEMPT_FAILURE = 'NEW_TEST_ATTEMPT_FAILURE'

export const SUBMIT_TEST_ATTEMPT = 'SUBMIT_TEST_ATTEMPT';
export const SUBMIT_TEST_ATTEMPT_SUCCESS = 'SUBMIT_TEST_ATTEMPT_SUCCESS';
export const SUBMIT_TEST_ATTEMPT_FAILURE = 'SUBMIT_TEST_ATTEMPT_FAILURE';


export const UPDATE_OBJECTIVE_QUESTION = 'UPDATE_OBJECTIVE_QUESTION';
export const UPDATE_SUBJECTIVE_QUESTION = 'UPDATE_SUBJECTIVE_QUESTION';

export const NEXT_QUESTION = 'NEXT_QUESTION';
export const PREVIOUS_QUESTION = 'PREVIOUS_QUESTION';