export const GET_UPCOMING_TESTS = 'GET_UPCOMING_TESTS'
export const GET_UPCOMING_TESTS_SUCCESS = 'GET_UPCOMING_TESTS_SUCCESS'
export const GET_UPCOMING_TESTS_FAILURE = 'GET_UPCOMING_TESTS_FAILURE'

export const GET_PAST_TESTS = 'GET_PAST_TESTS'
export const GET_PAST_TESTS_SUCCESS = 'GET_PAST_TESTS_SUCCESS'
export const GET_PAST_TESTS_FAILURE = 'GET_PAST_TESTS_FAILURE'

export const NEW_TEST_ATTEMPT = 'NEW_TEST_ATTEMPT'
export const NEW_TEST_ATTEMPT_SUCCESS = 'NEW_TEST_ATTEMPT_SUCCESS'
export const NEW_TEST_ATTEMPT_FAILURE = 'NEW_TEST_ATTEMPT_FAILURE'

export const SUBMIT_TEST_ATTEMPT = 'SUBMIT_TEST_ATTEMPT';
export const SUBMIT_TEST_ATTEMPT_SUCCESS = 'SUBMIT_TEST_ATTEMPT_SUCCESS';
export const SUBMIT_TEST_ATTEMPT_FAILURE = 'SUBMIT_TEST_ATTEMPT_FAILURE';


export const UPDATE_OBJECTIVE_QUESTION = 'UPDATE_OBJECTIVE_QUESTION';
export const UPDATE_SUBJECTIVE_QUESTION = 'UPDATE_SUBJECTIVE_QUESTION';

export const NEXT_QUESTION = 'NEXT_QUESTION';
export const PREVIOUS_QUESTION = 'PREVIOUS_QUESTION';
export const SELECT_QUESTION = 'SELECT_QUESTION';

export const GET_TEST_ATTEMPT_DETAILS = 'GET_TEST_ATTEMPT_DETAILS'
export const GET_TEST_ATTEMPT_DETAILS_SUCCESS = 'GET_TEST_ATTEMPT_DETAILS_SUCCESS'
export const GET_TEST_ATTEMPT_DETAILS_FAILURE = 'GET_TEST_ATTEMPT_DETAILS_FAILURE'